### ISSUE TITLE
Formula to determine safety level

### ISSUE THREAD

**Issue by wlinnp** [SoundsNeat/demo-web-project#4]
There should be an algorithm to decide how safe is that city?

Things to consider: 
- inclusion of category of crimes: 
- should crimes like domestic violence, homicides be included? 
- should the calculations backtrack only certain number of years or include all available data? 
  (i.e. the algorithm should backtrack only 3 years for each city or include all available data? )
- What is the baseline? 
- Should we take national average? 
- Should we take state average? 
- Should we have random 10 to 20 cities in that state and take their average?

**Comment by jtfetzer** [comment]
I wrote a method to pull all the cities in a state and save their json strings to file with the intention of using standard deviation to create a national average, however, pulling hundreds of requests caused a server time-out error. however, looking at the 400+ cities that I was able to get allowed me to create a pretty good metric for determining whether a city fell into one of four categories:   1 (very safe), 2 (mostly safe), 3 (somewhat dangerous), and 4 (very dangerous). The method takes an average of all the available years of statistical (crime/100k) data, creates a crimeIndex, then determines the amISafeIndex. Violent crimes are weighted more heavily.
