### ISSUE TITLE
Setting Up A Server

### ISSUE THREAD

**Issue by Lucodivo** [SoundsNeat/demo-web-project#7]
Are we going/Do we have to get a domain name and host it like a normal website?
Do we want to set up a AWS EC2 server in the mean time?

**Comment by wlinnp** [comment]
I believe if we can get free server space from Amazon, we just need to buy the domain name. That will be cheaper, I think. 
Need to confirm though.

**Comment by Lucodivo** [comment]
http://ec2-54-153-11-182.us-west-1.compute.amazonaws.com/

**Comment by wlinnp** [comment]
www.amisafehere.xyz
