### ISSUE TITLE
Jon's crime stat test is not working. 

### ISSUE THREAD

**Issue by wlinnp** [SoundsNeat/demo-web-project#9]
Jon & Connor, can you guys take a look what's happening at the error. 
I tweaked the old test code so it does not need arguments. 

While you are at it, may b you guys can rewrite the test case using JUnit.

**Comment by Lucodivo** [comment]
Works just fine for me. You might've had different versions of jackson-core and jackson-databind

**Comment by wlinnp** [comment]
Yes, it works.Just convert it to JUnit.

**Comment by Lucodivo** [comment]
I'm not sure the logic in some of the CrimeStats code makes sense

Ex: The following for getArsonStats

public float getArsonStats(int year) {
	for (int i = 0; i < crimeDataYears.length; i++) {
		if(arsonStats[i] == year){
			return arsonStats[i];
		} // end if
	} // end for i
	return -1; // data for year requested not available
}

Doesn't this either give you the year of the passed argument or -1? Doesn't really seem to make sense. I think there's a lot of copy pasta bugs in it. I'll try to fix it how I see fit.

**Comment by jtfetzer** [comment]
Re: getArsonStats

Not sure what's confusing. This method is overloaded. If you pass the year it will return the arson stats for that year, otherwise it returns an array of the arson stats for each year for which we have data, -1 if you pass a year for which we have no data.

**Comment by jtfetzer** [comment]
Good catch, all those methods should be changed to: if(crimeDataYears[i] == year)

**Comment by Lucodivo** [comment]
Ah, that's what I was thinking.

**Comment by Lucodivo** [comment]
I'm not sure OOP was necessary for the code clean-up of CrimeStats but I did cut out a lot of copy pasta. I believe it is much more flexible/readable now. I still need to refactor CreateCrimeStats. Haven't looked at it much.

**Comment by Lucodivo** [comment]
I'm making the decision not to use any real OOP designs. 

There is a question of why we even have a CreateCrimeStats class, instead of just including all the logic in CrimeStats. Regardless, I believe the code is very clean and manageable. Closing the issue.
